# Generated by Django 4.1.3 on 2022-11-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('detail', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
