# Generated by Django 4.1.3 on 2022-11-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='timezone.now', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='tacgia',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='detail',
            field=models.TextField(max_length=50000),
        ),
    ]
