# Generated by Django 4.1.3 on 2022-11-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_date_book_publisher_book_tacgia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='nhaxuatban',
        ),
    ]
